apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acme-app
  namespace: acmeproj
  labels: 
    app: acme-app
spec:
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
  selector:
    matchLabels:
      release: acme101
status: {}
