apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: acmeproj-prod
  namespace: acmeproj
  labels:
    app: acme-app
    release: acme101
spec:
  sourceNamespaces: 
  - acmeproj
  type: Namespace
  pathname: acmeproj
  gates:
    annotations:
      prod-ready: approved
